### ISSUE TITLE
Добавить методы аналитики

### ISSUE THREAD

**Issue by vadimsmirnovnsk** [teanet/Taksa#25]
- на тап в сагестор (от и до, от локейшена)
- на тап в выдачу
- на тап в город

**Comment by vadimsmirnovnsk** [comment]
@vidog

**Comment by Vidog** [comment]
**Headers:**
- `X-User-Id` - UID пользователя. Генерируется 1 раз и сохраняется в keychain
- `X-User-Session` - SID пользователя. Генерируется на каждую сессию.

И ты мне как-то скидывал:
- `@"X-Current-App-Build" : CURRENT_BUILD`
- `@"X-Current-App-Version" : CURRENT_VERSION`
- `@"X-Mobile-Vendor" : @"Apple"`
- `@"X-Mobile-Platform" : @"iOS"`
- `@"X-Mobile-Os-Version" : [[UIDevice currentDevice] systemVersion]`
- `@"X-Mobile-Model": [[UIDevice currentDevice] modelName]`

---

**Метод для регистрации событий:**
`POST /taksa/api/1.0/analytics?type={{type}}&region_id={{region_id}}`
`{{type}}` - тип сообщения
`{{region_id}}` - текущий регион
в теле реквеста json

---

**События:**
- type: `launch` _Вызывается после запуска приложения пользователем_

body:

``` javascript
// нет
```

---
- type: `suggest-select` _Вызывается при тыцке в результат саггеста_

body:

``` javascript
{
    "item_id": "12345", // id, в который ткнули
    "q": "ленин", // какой был поисковый запрос
    "type": "from", // поле: from или to
    "source": "location" // источник: location или q
}
```

---
- type: `city-select` _Вызывается при тыцке в город_

body:

``` javascript
{
    "region_id": "1" // id региона, который выбрали
}
```

---
- type: `taxi-select` _Вызывается при тыцке в результат подбора такси_

body:

``` javascript
{
    "search_id": 1, // id из поиска
    "operator_id": "uber", // id оператора, в который ткнули
    "type": "from", // поле: from или to
    "source": "location" // источник: location или q
}
```
